name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
        with:
          msystem: mingw64
          install: >-
            mingw-w64-x86_64-libusb

      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
        with:
          submodules: recursive

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: ${{ matrix.os == 'windows-latest' && 'MinGW Makefiles' || '' }}

      - name: Build the project
        run: cmake --build build --target ygo_card_tool --config Release

      - name: Test the project
        run: ctest --test-dir build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: bin
