name: Build
on:
  push:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Build the project
        runs: cmake --build . --target ygo_card_tool --config Release

      - name: Test the project
        runs: ctest --test-dir .

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0

      - name: Build the project
        runs: cmake --build . --target ygo_card_tool --config Release

      - name: Test the project
        runs: ctest --test-dir .
