name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
        with:
          submodules: recursive

      - name: Install LibUSB - Mac
        if: matrix.os == 'macos-latest'
        run: brew install libusb-compat

      - name: Install LibUSB - Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libusb-dev

      - name: Remove Strawberry - Windows
        if: matrix.os == 'windows-latest'
        run: rmdir /s /q C:\Strawberry
        shell: cmd

      - name: Configure MSVC x86
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows.latest'
        with:
          arch: x86

      - name: Run CMake - Windows
        if: matrix.os == 'windows-latest'
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: NMake Makefiles
          run-build: true

      - name: Run CMake - Unix
        if: matrix.os != 'windows-latest'
        uses: threeal/cmake-action@v1.3.0
        env:
          LIBRARY_PATH: /usr/local/lib
          LD_LIBRARY_PATH: /usr/local/lib
        with:
          run-build: true

      - name: Test the project
        run: ctest --test-dir build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: bin
